name: Sync with upstream repo

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Fetch upstream repository
        run: |
          git remote add upstream https://github.com/torikushiii/hoyolab-auto.git
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout main
          git rebase upstream/main || (echo "::error::Merge conflicts detected. Aborting!" && exit 1)

      - name: Push changes
        run: |
          git push origin main --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
